
import { Product, SchemaTable } from './types';

export const TRANSLATIONS = {
  ru: {
    appTitle: 'СтройЭкспресс',
    searchPlaceholder: 'Поиск материалов...',
    categories: 'Категории',
    wholesale: 'Оптом',
    retail: 'Розница',
    addToCart: 'В корзину',
    loaderService: 'Услуги грузчика',
    checkout: 'Оформить заказ',
    total: 'Итого',
    grandTotal: 'Общая сумма',
    minQty: 'Мин. кол-во:',
    soldMonthly: 'продано за месяц',
    leftInStock: 'в наличии',
    verifiedPurchase: 'Проверенный отзыв',
    pros: 'Плюсы',
    cons: 'Минусы',
    comment: 'Комментарий',
    allSpecs: 'Характеристики',
    reviews: 'Отзывы',
    appMode: 'Приложение',
    schemaMode: 'Архитектор',
    sellerMode: 'Продавец',
    adminMode: 'Админ',
    courierMode: 'Курьер',
    partnerProgram: 'Партнерка',
    referralText: 'Приглашайте друзей и получайте 1% от их заказов.',
    copyCode: 'Копировать код',
    yourOrder: 'Ваша корзина',
    emptyCart: 'В корзине пока пусто',
    lowStock: 'Мало на складе',
    buyRetail: 'Купить в розницу',
    orderWholesale: 'Заказать оптом',
    details: 'Подробнее',
    bestQuality: 'Лучшее качество',
    history: 'История заказов',
    favorites: 'Избранное',
    settings: 'Настройки',
    logout: 'Выйти',
    askSeller: 'Спросить',
    chatWithSeller: 'Чат с продавцом',
    techSupport: 'Техподдержка',
    supportOnline: 'Онлайн 24/7',
    home: 'Главная',
    materials: 'Материалы',
    tools: 'Инструменты',
    electrical: 'Электрика',
    finishing: 'Отделка'
  },
  uz: {
    appTitle: 'StroyExpress',
    searchPlaceholder: 'Qidirish...',
    categories: 'Kategoriyalar',
    wholesale: 'Ulgurji',
    retail: 'Chakana',
    addToCart: 'Savatga',
    loaderService: 'Yuk tashuvchi xizmati',
    checkout: 'Buyurtma berish',
    total: 'Jami',
    grandTotal: 'Umumiy summa',
    minQty: 'Min. miqdor:',
    soldMonthly: 'oyiga sotilgan',
    leftInStock: 'mavjud',
    verifiedPurchase: 'Tasdiqlangan sharh',
    pros: 'Afzalliklari',
    cons: 'Kamchiliklari',
    comment: 'Izoh',
    allSpecs: 'Xususiyatlari',
    reviews: 'Sharhlar',
    appMode: 'Ilova',
    schemaMode: 'Arxitektor',
    sellerMode: 'Sotuvchi',
    adminMode: 'Admin',
    courierMode: 'Kuryer',
    partnerProgram: 'Hamkorlik',
    referralText: 'Do\'stlarni taklif qiling va 1% balansingizga oling.',
    copyCode: 'Kodni nushalash',
    yourOrder: 'Sizning savatingiz',
    emptyCart: 'Savat bo\'sh',
    lowStock: 'Omborda kam',
    buyRetail: 'Chakana sotib olish',
    orderWholesale: 'Ulgurji buyurtma',
    details: 'Batafsil',
    bestQuality: 'Eng yaxshi sifat',
    history: 'Buyurtmalar tarixi',
    favorites: 'Saralanganlar',
    settings: 'Sozламalar',
    logout: 'Chiqish',
    askSeller: 'So\'rash',
    chatWithSeller: 'Sotuvchi bilan chat',
    techSupport: 'Texnik yordam',
    supportOnline: 'Onlayn 24/7',
    home: 'Asosiy',
    materials: 'Materiallar',
    tools: 'Asboblar',
    electrical: 'Elektr',
    finishing: 'Pardozlash'
  }
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'cement-m450',
    name: { ru: 'Цемент М450 Extra', uz: 'Sement M450 Extra' },
    category: 'materials',
    description: { ru: 'Высокопрочный портландцемент для ответственных конструкций.', uz: 'Yuqori mustahkamlikdagi sement.' },
    priceRetail: 45000,
    priceWholesale: 38000,
    wholesaleMinQty: 50,
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=400',
    sellerId: 's1',
    rating: 4.9,
    totalReviews: 128,
    soldLastMonth: 450,
    stock: 200,
    attributes: [{ key: 'weight', label: { ru: 'Вес', uz: 'Og\'irligi' }, value: '50 кг', isPrimary: true }]
  },
  {
    id: '5',
    slug: 'drill-makita',
    name: { ru: 'Дрель-шуруповерт Makita', uz: 'Makita drel-shurupoverti' },
    category: 'tools',
    description: { ru: 'Профессиональный инструмент для дома и стройки.', uz: 'Professional asbob.' },
    priceRetail: 1250000,
    priceWholesale: 1100000,
    wholesaleMinQty: 5,
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=400',
    sellerId: 's5',
    rating: 4.8,
    totalReviews: 56,
    soldLastMonth: 12,
    stock: 15,
    attributes: [{ key: 'voltage', label: { ru: 'Напряжение', uz: 'Kuchlanish' }, value: '18V', isPrimary: true }]
  },
  {
    id: '6',
    slug: 'grinder-bosch',
    name: { ru: 'УШМ Bosch GWS', uz: 'Bosch GWS bolgarkasi' },
    category: 'tools',
    description: { ru: 'Компактная углошлифовальная машина для резки металла.', uz: 'Yilcham bolgarka.' },
    priceRetail: 890000,
    priceWholesale: 820000,
    wholesaleMinQty: 3,
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&q=80&w=400',
    sellerId: 's2',
    rating: 4.7,
    totalReviews: 32,
    soldLastMonth: 8,
    stock: 22,
    attributes: [{ key: 'power', label: { ru: 'Мощность', uz: 'Quvvati' }, value: '720W', isPrimary: true }]
  },
  {
    id: '7',
    slug: 'cable-vvg',
    name: { ru: 'Кабель ВВГнг 3x2.5', uz: 'VVGng 3x2.5 kabeli' },
    category: 'electrical',
    description: { ru: 'Медный силовой кабель с негорючей изоляцией.', uz: 'Mis quvvat kabeli.' },
    priceRetail: 15000,
    priceWholesale: 12500,
    wholesaleMinQty: 100,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=400',
    sellerId: 's3',
    rating: 5.0,
    totalReviews: 12,
    soldLastMonth: 500,
    stock: 1000,
    attributes: [{ key: 'material', label: { ru: 'Материал', uz: 'Material' }, value: 'Медь', isPrimary: true }]
  },
  {
    id: '8',
    slug: 'hammer-tolsen',
    name: { ru: 'Молоток Tolsen 500г', uz: 'Tolsen bolg\'asi 500g' },
    category: 'tools',
    description: { ru: 'Качественный молоток с фиберглассовой ручкой.', uz: 'Sifatli bolg\'a.' },
    priceRetail: 65000,
    priceWholesale: 55000,
    wholesaleMinQty: 10,
    image: 'https://images.unsplash.com/photo-1586864387917-f729d0663731?auto=format&fit=crop&q=80&w=400',
    sellerId: 's1',
    rating: 4.5,
    totalReviews: 24,
    soldLastMonth: 40,
    stock: 150,
    attributes: [{ key: 'weight', label: { ru: 'Вес', uz: 'Og\'irligi' }, value: '500г', isPrimary: true }]
  },
  {
    id: '9',
    slug: 'paint-emulsion',
    name: { ru: 'Краска водоэмульсионная 10кг', uz: 'Suvli emulsiya bo\'yog\'i 10kg' },
    category: 'finishing',
    description: { ru: 'Матовая белая краска для внутренних работ.', uz: 'Ichki ishlar uchun oq bo\'yoq.' },
    priceRetail: 120000,
    priceWholesale: 105000,
    wholesaleMinQty: 5,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=400',
    sellerId: 's4',
    rating: 4.8,
    totalReviews: 45,
    soldLastMonth: 60,
    stock: 80,
    attributes: [{ key: 'volume', label: { ru: 'Объем', uz: 'Hajmi' }, value: '10кг', isPrimary: true }]
  }
];

export const DB_SCHEMA: SchemaTable[] = [
  {
    name: 'Products',
    description: 'Catalog of construction materials and tools',
    columns: [
      { name: 'id', type: 'UUID', key: 'PK', description: 'Primary Key' },
      { name: 'name_ru', type: 'String', description: 'Name in Russian' },
      { name: 'category', type: 'String', description: 'Category (tools, materials, etc)' },
      { name: 'price_retail', type: 'Decimal', description: 'Retail price' },
      { name: 'stock_qty', type: 'Integer', description: 'Available stock' }
    ]
  },
  {
    name: 'Orders',
    description: 'Customer order tracking',
    columns: [
      { name: 'id', type: 'UUID', key: 'PK', description: 'Order ID' },
      { name: 'user_id', type: 'UUID', key: 'FK', description: 'Customer Reference' },
      { name: 'total_amount', type: 'Decimal', description: 'Total price' },
      { name: 'status', type: 'Enum', description: 'Pending, Paid, Delivered' }
    ]
  }
];
